# Eureka client configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
# Spring Security configuration
# okta:
#   oauth2:
#     issuer-uri: https://dev-42887115.okta.com/oauth2/default
#     audience: api://default
security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: https://dev-42887115.okta.com/oauth2/default
    client:
      provider:
        okta:
          issuer-uri: https://dev-42887115.okta.com/oauth2/default
